KisiselWebProjesi/Models/Siniflar/Admin.cs
using System.ComponentModel.DataAnnotations;

namespace KisiselWebProjesi.Models.Siniflar
{
    public class Admin
    {
        [Key]
        public int id { get; set; }
        public string kullaniciadi { get; set; }

        public string sifre { get; set; }
    }
}

KisiselWebProjesi/Models/Siniflar/AnaSayfa.cs
using System.ComponentModel.DataAnnotations;

namespace KisiselWebProjesi.Models.Siniflar
{
    public class AnaSayfa
    {
        [Key]
        public int id { get; set; }
        public string profil { get; set; }

        public string isim { get; set; }
        public string unvan { get; set; }

        public string aciklama { get; set; }

        public string iletisim { get; set; }

        
    }
}

KisiselWebProjesi/Models/Siniflar/Context.cs
using System.Data.Entity;

namespace KisiselWebProjesi.Models.Siniflar
{
    public class Context :DbContext
    {
        public DbSet<Admin> Admins { get; set; }
        public DbSet<AnaSayfa> AnaSayfas {  get; set; } 
        public DbSet<ikonlar> İkonlars { get; set; }
    }
}

KisiselWebProjesi/Models/Siniflar/ikonlar.cs
using System.ComponentModel.DataAnnotations;

namespace KisiselWebProjesi.Models.Siniflar
{
    public class ikonlar
    {
        [Key]
        public int id { get; set; }
        public string ikon { get; set; }
        public string link { get; set; }
        
    }
}

KisiselWebProjesi/Controllers/AdminController.cs
using KisiselWebProjesi.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KisiselWebProjesi.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin

        Context  c = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var deger = c.AnaSayfas.ToList();
            return View(deger);
        }

        public ActionResult AnaSayfaGetir(int id)
        {
            var ag = c.AnaSayfas.Find(id);
            return View("AnaSayfaGetir",ag);
        }

        public ActionResult AnaSayfaGüncelle(AnaSayfa x)
        {
            var ag = c.AnaSayfas.Find(x.id);
            ag.isim = x.isim;
            ag.profil = x.profil;
            ag.unvan = x.unvan;
            ag.aciklama = x.aciklama;
            ag.iletisim = x.iletisim;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult İkonListesi()
        {
            var deger = c.İkonlars.ToList();
            return View(deger);
        }

        public ActionResult YeniIkon()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniIkon(ikonlar p)
        {
            c.İkonlars.Add(p);
            c.SaveChanges();
            return RedirectToAction("İkonListesi");
        }

        public ActionResult İkonGetir(int id)
        {
            var ig = c.İkonlars.Find(id);
            return View("İkonGetir",ig);
        }

        public ActionResult İkonGuncelle(ikonlar x)
        {
            var ig = c.İkonlars.Find(x.id);
            ig.ikon = x.ikon;
            ig.link = x.link;
            c.SaveChanges();
            return RedirectToAction("İkonListesi");
        }

        public ActionResult İkonSil(int id)
        {
            var sl = c.İkonlars.Find(id);
            c.İkonlars.Remove(sl);
            c.SaveChanges();
            return RedirectToAction("İkonListesi");
        }
    }
}

KisiselWebProjesi/Controllers/AnaSayfaController.cs
using KisiselWebProjesi.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KisiselWebProjesi.Controllers
{
    public class AnaSayfaController : Controller
    {
        // GET: AnaSayfa
        Context c = new Context();
        public ActionResult Index()
        {
            var deger = c.AnaSayfas.ToList();
            return View(deger);
        }

        public PartialViewResult ikonlar()
        {
            var deger = c.İkonlars.ToList();
            return PartialView(deger); 
        }

    }
}

KisiselWebProjesi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KisiselWebProjesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KisiselWebProjesi/Controllers/LoginController.cs
using KisiselWebProjesi.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace KisiselWebProjesi.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Context c = new Context();
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Admin ad)
        {
            var bilgiler = c.Admins.FirstOrDefault(x=> x.kullaniciadi == ad.kullaniciadi && x.sifre ==ad.sifre);
            if(bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.kullaniciadi,false);
                Session["kullaniciadi"] = bilgiler.kullaniciadi.ToString();
                return RedirectToAction("Index","Admin");
            }
            else
            {
                return View();
            }
        }
        public ActionResult LogOut()
        {
                 FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Login");
        }

    }
}

KisiselWebProjesi/Views/Admin/AnaSayfaGetir.cshtml
@model KisiselWebProjesi.Models.Siniflar.AnaSayfa


@{
    ViewBag.Title = "AnaSayfaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Ana Sayfa Güncelle</h2>
<hr />

@using (Html.BeginForm("AnaSayfaGüncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id)
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.isim)
    @Html.TextBoxFor(x => x.isim, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.unvan)
    @Html.TextBoxFor(x => x.unvan, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.aciklama)
    @Html.TextAreaFor(x => x.aciklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.iletisim)
    @Html.TextBoxFor(x => x.iletisim, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Ana Sayfa Güncelle</button>
}

KisiselWebProjesi/Views/Admin/Index.cshtml
@using KisiselWebProjesi.Models.Siniflar
@model List<AnaSayfa>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Ana Sayfa</h2>
<table class="table table-bordered mt-3">
    <tr>
        <th>Id</th>
        <th>İsim</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.isim</td>
            <td><a href="~/Admin/AnaSayfaGetir/@x.id" class="btn btn-primary">Güncelle</a></td>
        </tr>
    }


</table>
  

  

KisiselWebProjesi/Views/Admin/YeniIkon.cshtml
@model KisiselWebProjesi.Models.Siniflar.ikonlar
@{
    ViewBag.Title = "YeniIkon";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Ikon Ekle</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.ikon)
    @Html.TextBoxFor(x => x.ikon, new { @class = "form-control " })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control " })
    <br />
    <button class="btn btn-success">İkon Ekle</button>
</form>

KisiselWebProjesi/Views/Admin/İkonGetir.cshtml
@model KisiselWebProjesi.Models.Siniflar.ikonlar
@{
    ViewBag.Title = "İkonGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>İkon Güncelle</h2>
<br />

@using (Html.BeginForm("İkonGüncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id)
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.ikon)
    @Html.TextBoxFor(x => x.ikon, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control" })
    <br />

    <button class="btn btn-success">İkon Güncelle</button>
}

KisiselWebProjesi/Views/Admin/İkonListesi.cshtml
@using KisiselWebProjesi.Models.Siniflar
@model List<ikonlar>
@{
    ViewBag.Title = "İkonListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



    <h2 class="mb-4"İkonlar Sayfası</h2>
<table class="table table-bordered"> 
    <tr>
        <th>Id</th>
        <th>Ikon</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>

    @foreach (var x in Model) 
     {
         <tr>
            <td>@x.id</td>
             <td><i class ="@x.ikon"></i></td>
             <td><a href="/Admin/İkonGetir/@x.id" class="btn btn-primary">Güncelle</a></td>
             <td><a href="/Admin/İkonSil/@x.id" class="btn btn-danger">Sil</a></td>
         </tr>
     }
</table>

<a href="/Admin/YeniIkon" class="btn btn-primary">Yeni İkon Ekle</a>

KisiselWebProjesi/Views/AnaSayfa/Index.cshtml
@using KisiselWebProjesi.Models.Siniflar
@model List<AnaSayfa>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/web-KişiselWebSitesi/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <title>Kişisel web sitesi </title>
</head>
<body>
    <div class="center">
        <div class="avatar">
            @foreach (var x in Model)
            {
                <img src="~/web-KişiselWebSitesi/WhatsApp Image 2024-12-24 at 17.09.50.jpeg">
            }


        </div>
        <div class="content">
            @foreach (var x in Model)
            {
                <h1>Nuri Kaplan</h1>
                <h2>@x.unvan</h2> 
                <p> @x.aciklama.</p>
                <h3>@x.iletisim</h3>

            }
        </div>
        @Html.Action("ikonlar","AnaSayfa")
        

</body>
</html>

KisiselWebProjesi/Views/AnaSayfa/ikonlar.cshtml
@using KisiselWebProjesi.Models.Siniflar;
@model List<ikonlar>




<div class="social">
    @foreach (var x in Model)
    {
        <a href="@x.link"><i class="@x.ikon"></i></a>
        
    }

</div>

KisiselWebProjesi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

KisiselWebProjesi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

KisiselWebProjesi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

KisiselWebProjesi/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel Login</title>
    <link rel="stylesheet" href="~/web-Admin-Login/style.css">
</head>
<body>
    <div class="container">
        <div class="contach-form">
            <img src="~/web-Admin-Login/9703596.png" class="admin-img">

            <h2>Admin Login</h2>
            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
            {


                <div class="txtb">
                    <input type="text" name="kullaniciadi" placeholder="Username">
                </div>

                <div class="txtb">
                    <input type="password" name="sifre" placeholder="Password">
                </div>

                <input type="submit" class="logbtn" value="Login">
            }

        </div>
    </div>


</body>
</html>

KisiselWebProjesi/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <title>Admin Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap-grid.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">

</head>
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
        <h3 class="w3-bar-item">Admin Panel</h3>
        <a href="/Admin/Index" class="w3-bar-item w3-button">Ana Sayfa</a>
        <a href="/Admin/İkonListesi" class="w3-bar-item w3-button">İkonlar</a>
        <a href="/AnaSayfa/Index" target="_blank" class="w3-bar-item w3-button btn-info">Siteye git</a>
        <a href="/Login/LogOut" class="w3-bar-item w3-button btn-danger">Çıkış</a>

    </div>

    <!-- Page Content -->
    <div style="margin-left:25%">

        <div class="w3-container w3-teal" style="background: linear-gradient(#141e30, #243b55);">
            <h1 style="color : white;">Kişisel Web Sitesi</h1>
        </div>



        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" >
    </script>


</body>
</html>

KisiselWebProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>